### ISSUE TITLE
Triangle won't compile.. "error: triangle/core.c: No such file or directory"

### ISSUE THREAD

**Issue by federicohyo** [drufat/triangle#12]
Hi there,

I just downloaded the git repository and tried to install it. However I am experiencing the following problem. Any suggestions?

federico@zfractal:~/Downloads/triangle$ pwd
/home/federico/Downloads/triangle
federico@zfractal:~/Downloads/triangle$ ls
build  c  CHEATSHEET  doc  MANIFEST.in  README.rst  release.sh  setup.py  triangle  triangle.egg-info  upload_docs.sh
federico@zfractal:~/Downloads/triangle$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to triangle.egg-info/requires.txt
writing triangle.egg-info/PKG-INFO
writing top-level names to triangle.egg-info/top_level.txt
writing dependency_links to triangle.egg-info/dependency_links.txt
reading manifest file 'triangle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'triangle.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
pyrexc triangle/core.pyx --> triangle/core.c
/home/federico/Downloads/triangle/triangle/core.pyx:5:35: Expected an identifier or literal
building 'triangle.core' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVOID=int -DREAL=double -DNO_TIMER=1 -DTRILIBRARY=1 -DANSI_DECLARATORS=1 -Ic -I/usr/include/python2.7 -c c/triangle.c -o build/temp.linux-x86_64-2.7/c/triangle.o
c/triangle.c:3267:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void internalerror()
      ^
c/triangle.c:4886:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void exactinit()
      ^
c/triangle.c: In function ‘segmentintersection’:
c/triangle.c:11707:28: warning: variable ‘collinear’ set but not used [-Wunused-but-set-variable]
   enum finddirectionresult collinear;
                            ^
c/triangle.c: In function ‘tallyencs’:
c/triangle.c:13184:7: warning: variable ‘dummy’ set but not used [-Wunused-but-set-variable]
   int dummy;
       ^
c/triangle.c: At top level:
c/triangle.c:13206:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void precisionerror()
      ^
c/triangle.c: In function ‘splitencsegs’:
c/triangle.c:13257:7: warning: variable ‘dummy’ set but not used [-Wunused-but-set-variable]
   int dummy;
       ^
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVOID=int -DREAL=double -DNO_TIMER=1 -DTRILIBRARY=1 -DANSI_DECLARATORS=1 -Ic -I/usr/include/python2.7 -c triangle/core.c -o build/temp.linux-x86_64-2.7/triangle/core.o
x86_64-linux-gnu-gcc: error: triangle/core.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

**Comment by drufat** [comment]
For some reason on your system triangle/core.pyx does not get converted to triangle/core.c. Do you have Cython installed?

**Comment by tfabbri** [comment]
I think the fix that I posted should work also in this case.

**Comment by LonelyDeer** [comment]
Hello, @drufat. I have the same error. 
Here is my listing (There are some Russian words in name of directories, but it's just the same content).

running install
running bdist_egg
running egg_info
writing requirements to triangle.egg-info/requires.txt
writing triangle.egg-info/PKG-INFO
writing top-level names to triangle.egg-info/top_level.txt
writing dependency_links to triangle.egg-info/dependency_links.txt
reading manifest file 'triangle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'triangle.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
pyrexc triangle/core.pyx --> triangle/core.c
/home/lira/Загрузки/triangle-master/triangle/core.pyx:5:35: Expected an identifier or literal
building 'triangle.core' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVOID=int -DREAL=double -DNO_TIMER=1 -DTRILIBRARY=1 -DANSI_DECLARATORS=1 -Ic -I/usr/include/python2.7 -c c/triangle.c -o build/temp.linux-x86_64-2.7/c/triangle.o
c/triangle.c:3267:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void internalerror()
      ^
c/triangle.c:4886:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void exactinit()
      ^
c/triangle.c: In function ‘segmentintersection’:
c/triangle.c:11707:28: warning: variable ‘collinear’ set but not used [-Wunused-but-set-variable]
   enum finddirectionresult collinear;
                            ^
c/triangle.c: In function ‘tallyencs’:
c/triangle.c:13184:7: warning: variable ‘dummy’ set but not used [-Wunused-but-set-variable]
   int dummy;
       ^
c/triangle.c: At top level:
c/triangle.c:13206:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void precisionerror()
      ^
c/triangle.c: In function ‘splitencsegs’:
c/triangle.c:13257:7: warning: variable ‘dummy’ set but not used [-Wunused-but-set-variable]
   int dummy;
       ^
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVOID=int -DREAL=double -DNO_TIMER=1 -DTRILIBRARY=1 -DANSI_DECLARATORS=1 -Ic -I/usr/include/python2.7 -c triangle/core.c -o build/temp.linux-x86_64-2.7/triangle/core.o
x86_64-linux-gnu-gcc: error: triangle/core.c: Нет такого файла или каталога
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

 I've installed (in order of errors that came in during installation):
setuptools 
python-dev
Cython 0.2
python-pyrex

Linux Mint 17.2

**Comment by JohnCC330** [comment]
Basically, I have the same problem. The original .tar.gz contains a triangle/core.pyx which causes the message:
`error: unknown file type '.pyx' (from 'triangle/core.pyx')`
I thought Pyrex wasn't necessary for the project (I read it was replaced by Cython).

**Comment by sinback** [comment]
I was also having the issue described by the first two complainants (after getting Cython version 0.24) on Ubuntu 14.04. I managed to resolve it by uninstalling my system's setuptools (version 3.3) and getting the latest version of setuptools with pip (version 23.0) (what a difference, jeez!!) Since Ubuntu's pip depends on python-setuptools, I also had to reinstall pip not through apt but through the maintainers' own installation script:

`sudo apt-get remove python-setuptools
wget https://bootstrap.pypa.io/get-pip.py
sudo -H pip install -U pip setuptools`

Now, the following error when installing triangle was encountered:

`Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extern.six.moves import filterfalse, map
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named extern
`

so after some googling, I also did: 

`sudo apt-get purge python-pkg-resources
sudo apt-get -f install`

(the second step didn't seem necessary in my case, but it can't hurt)

Now, I can install triangle both by cloning the git repo and running `python setup.py install` and by using `sudo -H pip install triangle`.

**Comment by LonelyDeer** [comment]
@sinback, thank you very much! It really works. But can you explain it to me? What did we do?
1. `sudo apt-get remove python-setuptools` 
ok, we just removed setuptools (and pip too, look item 3)
2. `wget https://bootstrap.pypa.io/get-pip.py` 
we said "Hey, Linux - loook there" - we have inserted new repository
3. `sudo -H pip install -U pip setuptools` 
I don't what is `-H` and "-U". Than `pip install` is a command to use pip to install a package `pip setuptools`. Is here a mistake? Because this string call an error like "unknown command pip". 
I'have installed pip by `python get-pip.py` with file get-pip.py from [this site](https://pip.pypa.io/en/stable/installing/). Then i've did 
`sudo apt-get purge python-pkg-resources` 
`sudo apt-get -f install`
`sudo -H pip install triangle`

And all works. Thank you @sinback. Thank you @drufat.
