### ISSUE TITLE
Clarification of LICENSE

### ISSUE THREAD

**Issue by smithsp** [drufat/triangle#15]
@drufat 
Please clarify your license. Which version of LGPL do you refer to?

**Comment by drufat** [comment]
Since this is a wrapper around the C triangle library

https://www.cs.cmu.edu/~quake/triangle.html

ideally it should inherit the same license. However, there is no mention of a specific license on the triangle website, other than:

> Please note that although Triangle is freely available, it is copyrighted by the author and may not be sold or included in commercial products without a license. 

Obviously, I can license only my own code, and for that I would use LGPLv3, but that would not cover the triangle C source code which the python module wraps. If you prefer a different type of license, I am open to changing the license to my code.

**Comment by smithsp** [comment]
@drufat Thanks.
